[project]
name = "Indian_Unemployment_Dashboard"
version = "1.0.0"
description = "An interactive Streamlit dashboard visualizing unemployment trends in India."
requires-python = ">=3.8"
dependencies = [
    "pandas>=2.0.0",
    "plotly>=5.0.0",
    "streamlit>=1.25.0",
]
